NutriSoftwareV1/Controllers/AnmineseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NutriSoftwareV1.Data;
using NutriSoftwareV1.Models;

namespace NutriSoftwareV1.Controllers
{
    public class AnmineseController : Controller
    {
        public IActionResult Index(long Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var anminese = db.Anminese
                    .Include(d => d.DiagnosticoMedico)
                    .Include(s => s.HistoricoFamiliar)
                    .Include(a => a.AtividadesFiscia)
                    .Include(p => p.Paciente)
                    .FirstOrDefault(p => p.PacienteId == Id);
                ViewBag.Id = Id;

                return View(anminese);
            }

        }

        [HttpGet]
        public IActionResult CadastrarEditarAnminese(long Id, int? AnmineseId = null)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                ViewBag.Titulo = "Cadastro de Anminese";
                if (AnmineseId.HasValue)
                {
                    var anminese = db.Anminese.Find(AnmineseId);
                    ViewBag.DiagnosticoMedico = ListaDoencas(db, anminese.DiagnosticoMedicoId);
                    ViewBag.HistoricoFamiliar = ListaDoencas(db, anminese.HistoricoFamiliarId);
                    ViewBag.AtividadesFisicas = ListaAtividadesFisicas(db, anminese.AtividadesFisciaId);
                    ViewBag.Titulo = "Alterar dados de  Anminese";
                    ViewBag.PacienteId = Id;
                    ViewBag.Id = Id;
                    return PartialView("Partiais/_FormularioAnminese", anminese);

                }
                ViewBag.PacienteId = Id;
                ViewBag.Id = Id;
                ViewBag.DiagnosticoMedico = ListaDoencas(db);
                ViewBag.HistoricoFamiliar = ListaDoencas(db);
                ViewBag.AtividadesFisicas = ListaAtividadesFisicas(db);
                return PartialView("Partiais/_FormularioAnminese");
            }
        }


        [HttpPost]
        public IActionResult CadastrarEditarAnminese(Anminese pAnminese)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                if (pAnminese.Id > 0)
                    db.Anminese.Update(pAnminese);
                else
                    db.Anminese.Add(pAnminese);

                db.SaveChanges();
                var anminese = db.Anminese.Include(d => d.DiagnosticoMedico)
                    .Include(s => s.HistoricoFamiliar)
                    .Include(a => a.AtividadesFiscia)
                    .Include(p => p.Paciente)
                    .FirstOrDefault(p => p.PacienteId == pAnminese.PacienteId);
                ViewBag.Id = pAnminese.PacienteId;
                return PartialView("Partiais/_GeralAnminese", anminese);
            }
        }
        public static SelectList ListaDoencas(NutriDbContext db, int? IdDoenca = null)
        {
            var doecas = db.Doenca.ToList();
            return new SelectList(doecas, "Id", "Descricao", IdDoenca);
        }

        public static SelectList ListaAtividadesFisicas(NutriDbContext db, int? IdAtividade = null)
        {
            var doecas = db.AtividadeFisica.ToList();
            return new SelectList(doecas, "Id", "Descricao", IdAtividade);
        }
    }
}

NutriSoftwareV1/Controllers/AvaliacaoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NutriSoftwareV1.Data;
using NutriSoftwareV1.Dto;
using NutriSoftwareV1.Models;
using System.Text.Json;

namespace NutriSoftwareV1.Controllers
{
    public class AvaliacaoController : Controller
    {
        ErrorMessage errorMessage;
        public IActionResult Index(long Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var pacienteAvaliacoes = db.pacientes.Include(p => p.Avaliacoes).FirstOrDefault(p => p.Id == Id);
                return View(pacienteAvaliacoes);
            }
        }

        [HttpGet]
        public IActionResult CadastrarEditarAvaliacaoFisica(long Id, long? AvaliacoaId)
        {
            DtoCadastroAvaliacaoFisica dtoCadastroAvaliacaoFisica = new DtoCadastroAvaliacaoFisica();
            dtoCadastroAvaliacaoFisica.PacienteId = Id;
            dtoCadastroAvaliacaoFisica.TituloCadastarEditar = "Cadastrar Avaliação";
            dtoCadastroAvaliacaoFisica.Data = DateTime.Now;

            using (NutriDbContext db = new NutriDbContext())
            {
                var avaliacoes = db.AvaliacoesFisicas?.Include(p => p.Paciente)?.Where(p => p.PacienteId == Id)?.OrderBy(p => p.Consulta);

                if (AvaliacoaId.HasValue)
                {
                   
                    dtoCadastroAvaliacaoFisica.TituloCadastarEditar = "Editar Avaliação";
                    dtoCadastroAvaliacaoFisica.CriarAtulizar = db.AvaliacoesFisicas.Find(AvaliacoaId.Value);
                    var avaliacaoAnterior = dtoCadastroAvaliacaoFisica.CriarAtulizar.Consulta - 1;
                    dtoCadastroAvaliacaoFisica.NumeroAvaliacao = dtoCadastroAvaliacaoFisica.CriarAtulizar.Consulta;
                    dtoCadastroAvaliacaoFisica.Data = dtoCadastroAvaliacaoFisica.CriarAtulizar.DataAvaliacao;
                    dtoCadastroAvaliacaoFisica.UltimaAvalicao = db.AvaliacoesFisicas?.Include(p => p.Paciente)?.FirstOrDefault(p => p.Consulta == avaliacaoAnterior);
                    return PartialView("Partiais/_FormularioAvaliacao", dtoCadastroAvaliacaoFisica);
                }
               
                dtoCadastroAvaliacaoFisica.UltimaAvalicao = avaliacoes?.LastOrDefault();
                dtoCadastroAvaliacaoFisica.NumeroAvaliacao = avaliacoes.Count() + 1;
            }
            return PartialView("Partiais/_FormularioAvaliacao", dtoCadastroAvaliacaoFisica);


        }


        [HttpPost]
        public IActionResult CadastrarEditarAvaliacaoFisica(AvaliacaoFisica pAvaliacao)
        {
            if (!ModelState.IsValid)
            {
                errorMessage = new ErrorMessage();
                errorMessage.TituloErro = "validação(es)";
                ModelState.Values.Where(e => e.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid).ToList().ForEach(p =>
                {
                    errorMessage.MensagemDeErro += p.Errors[0].ErrorMessage;
                });

                string jsonStr = JsonSerializer.Serialize<ErrorMessage>(errorMessage);
                return StatusCode(500, jsonStr);
            }

            using (NutriDbContext db = new NutriDbContext())
            {
                if (pAvaliacao?.Id > 0)
                    db.AvaliacoesFisicas.Update(pAvaliacao);
                else
                    db.AvaliacoesFisicas.Add(pAvaliacao);
                db.SaveChanges();
                return PartialView("Partiais/_ListaAvaliacoes", db.AvaliacoesFisicas.Include(p => p.Paciente).Where(p => p.PacienteId == pAvaliacao.PacienteId).ToList());
            }
        }

        [HttpPost]
        public IActionResult Delete(long Id)
        {
            try
            {

                using (NutriDbContext db = new NutriDbContext())
                {
                    var avaliacao = db.AvaliacoesFisicas.Find(Id);
                    var pacienteId = avaliacao.PacienteId;
                    db.Remove(avaliacao);
                    db.SaveChanges();

                    return PartialView("Partiais/_ListaAvaliacoes", db.AvaliacoesFisicas.Include(p => p.Paciente).Where(p => p.PacienteId == pacienteId).ToList());
                }
            }catch (Exception ex)
            {
                errorMessage = new ErrorMessage();
                errorMessage.TituloErro = "Exception";
                errorMessage.MensagemDeErro = !string.IsNullOrEmpty(ex?.InnerException?.Message)? ex.InnerException.Message : ex.Message;
                string jsonStr = JsonSerializer.Serialize<ErrorMessage>(errorMessage);
                return StatusCode(500, jsonStr);
            }
        }
    }
}

NutriSoftwareV1/Controllers/PacienteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NutriSoftwareV1.Data;
using NutriSoftwareV1.Models;
using Org.BouncyCastle.Asn1.Ocsp;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace NutriSoftwareV1.Controllers
{
    public class PacienteController : Controller
    {
        ErrorMessage errorMessage;

        [HttpGet]
        public IActionResult Index(long? Id, bool requestJs = false)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var pacientes = db.pacientes.Include(p => p.Anotacoes).OrderBy(p => p.Nome).ToList();
                if (Id.HasValue)
                {
                    ViewBag.DetalhePaciente = Id.Value;
                    ViewBag.DetalhePaciente = pacientes.FirstOrDefault(p => p.Id == Id.Value);
                    if (requestJs)
                        return PartialView("Partiais/_DetalhesPaciente", pacientes.FirstOrDefault(p => p.Id == Id.Value));
                }
                return View(pacientes);
            }
        }

        public IActionResult CadastrarEditarPaciente(long? Id)
        {
            using (NutriDbContext db =new NutriDbContext())
            {
                if (Id.HasValue)
                {
                    return PartialView("Partiais/_FormularioCadastrarEditarPaciente", db.pacientes.Find(Id));
                }
                return PartialView("Partiais/_FormularioCadastrarEditarPaciente", new Paciente());
            }
        }

        [HttpPost]
        public IActionResult Create(Paciente pPaciente)
        {
            if (!ModelState.IsValid)
            {
                errorMessage = new ErrorMessage();
                errorMessage.TituloErro = " validação(es)";
                ModelState.Values.Where(e => e.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid).ToList().ForEach(p =>
                {
                    errorMessage.MensagemDeErro += p.Errors[0].ErrorMessage;
                });

                string jsonStr = JsonSerializer.Serialize<ErrorMessage>(errorMessage);
                return StatusCode(500, jsonStr);
            }
            using (NutriDbContext db = new NutriDbContext())
            {
                pPaciente.Cpf = string.IsNullOrEmpty(pPaciente.Cpf) ? null : pPaciente.Cpf.Replace(".", "").Replace("-", "");

                db.pacientes.Add(pPaciente);
                db.SaveChanges();
                var pacienteCadastrado = db.pacientes.FirstOrDefault(p => p.Id == pPaciente.Id);

                return PartialView("Partiais/_DetalhesPaciente", pacienteCadastrado);
            }
        }

        [HttpPost]
        public IActionResult Edit(Paciente pPaciente)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                if (!string.IsNullOrEmpty(pPaciente.Cpf))
                    pPaciente.Cpf = pPaciente.Cpf.Replace(".", "").Replace("-", "");

                if (!string.IsNullOrEmpty(pPaciente.Telefone))
                    pPaciente.Telefone = RemoverMascaraTelefone(pPaciente.Telefone);
                db.pacientes.Update(pPaciente);
                db.SaveChanges();
                var pacienteCadastrado = db.pacientes.FirstOrDefault(p => p.Id == pPaciente.Id);

                return PartialView("Partiais/_DetalhesPaciente", pacienteCadastrado);
            }
        }


        [HttpPost]
        public IActionResult Delete(long Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var paciente = db.pacientes.Find(Id);
                var anotacoes = db.AnotacosPaciente.Where(p => p.PacienteId == Id).ToList();
                var avaliacoes = db.AvaliacoesFisicas.Where(p => p.PacienteId == Id).ToList();
                var avaliacoesBio = db.AvalicaoBioImpedancia.Where(p => p.PacienteId == Id).ToList();
                if (anotacoes.Count > 0)
                    db.AnotacosPaciente.RemoveRange(anotacoes);

                if (avaliacoes.Count > 0)
                    db.AvaliacoesFisicas.RemoveRange(avaliacoes);

                if (avaliacoesBio.Count > 0)
                    db.AvalicaoBioImpedancia.RemoveRange(avaliacoesBio);

                db.pacientes.Remove(paciente);
                db.SaveChanges();
                var pacientes = db.pacientes.OrderBy(p => p.Nome).ToList();

                return PartialView("Partiais/_GeralPaciente", pacientes);
            }
        }


        #region Anotacões
        public IActionResult ObservacoesPaciente(long Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var anotacoes = db.pacientes.Include(p => p.Anotacoes).FirstOrDefault(p => p.Id == Id);
                var pacienteAnotacoes = anotacoes == null ? new Paciente { Id = Id } : anotacoes;
                return PartialView("Partiais/_AnotacoesPaciente", pacienteAnotacoes);
            }
        }

        [HttpGet]
        public IActionResult CadastrarAnotacaoPaciente(int Id)
        {
            ViewBag.TitleModalAnotacoes = "Cadastro de anotações";
            ViewBag.BotaoTituloCadastroAnotacoes = "Salvar";
            ViewBag.DetalhePaciente = Id;
            return PartialView("Partiais/_FormularioCadastrarEditarAnotacaoPaciente", new Observacao { PacienteId = Id, DataObservacao=DateTime.Now});

        }
        [HttpPost]
        public IActionResult CadastrarAnotacaoPaciente(Observacao pAnotacao)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                db.AnotacosPaciente.Add(pAnotacao);
                db.SaveChanges();
                var anotacoesPaciente = db.pacientes.Include(p => p.Anotacoes).FirstOrDefault(p=>p.Id == pAnotacao.PacienteId);

                return PartialView("Partiais/_AnotacoesPaciente", anotacoesPaciente);
            }
        }
        [HttpGet]
        public IActionResult EditarAnotacaoPaciente(int Id)
        {
            ViewBag.TitleModalAnotacoes = "Alteração de anotação";
            ViewBag.BotaoTituloCadastroAnotacoes = "Salvar alterações";
            using (NutriDbContext db = new NutriDbContext())
            {
                var anotacao = db.AnotacosPaciente.Include(p => p.Paciente).FirstOrDefault(p => p.Id == Id);

                return PartialView("Partiais/_FormularioCadastrarEditarAnotacaoPaciente", anotacao);
            }
        }

        [HttpPost]
        public IActionResult EditarAnotacaoPaciente(Observacao pAnotacao)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                db.AnotacosPaciente.Update(pAnotacao);
                db.SaveChanges();
                var anotacoesPaciente = db.pacientes.Include(a=>a.Anotacoes).FirstOrDefault(p=>p.Id==pAnotacao.PacienteId);
                return PartialView("Partiais/_AnotacoesPaciente", anotacoesPaciente);
            }
        }

        [HttpPost]
        public IActionResult RemoverAnotacaoPaciente(int Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var anotacao = db.AnotacosPaciente.Find(Id);
                var idPaciente = anotacao.PacienteId;
                db.AnotacosPaciente.Remove(anotacao);
                db.SaveChanges();
                var anotacoesPaciente = db.pacientes.Include(a=>a.Anotacoes).FirstOrDefault(p=>p.Id== idPaciente);
                return PartialView("Partiais/_AnotacoesPaciente", anotacoesPaciente);
            }
        }


        #endregion

        public static string RemoverMascaraTelefone(string telefone)
        {
            // Remove caracteres não numéricos
            string numeroLimpo = Regex.Replace(telefone, @"[^\d]", "");

            return numeroLimpo;
        }

    }
}

NutriSoftwareV1/Views/Consumos/Partiais/_DadosConsumoAlimentar.cshtml
@model ConsumoAlimentar
@if (Model != null)
{
    <div class="col-12 bg-secondary p-1 bdr-5"><h5 class="text-center text-light p-0 m-0">Paciente: <b>@Model.Paciente.Nome</b></h5></div>
    <div class="col-12 p-0">
        <div class="row">

            <div class="col-12 p-0 d-inline-block mt-1">
                <div class="container-fluid mt-1 pe-0">
                    
                    <div class="row">
                        <div class="col-4">
                            <label>Água</label>
                            <input type="text" readonly value="@Model.Agua" class="form-control form-control-sm" />
                        </div>
                        <div class="col-8">
                            <br />
                            <input type="text" readonly value="@Model?.ObsAgua" class="form-control form-control-sm" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <label>Sucos</label>
                            <input type="text" readonly value="@Model?.Sucos" class="form-control form-control-sm" />
                        </div>
                        <div class="col-8">
                            <br />
                            <input type="text" readonly value="@Model?.ObsSucos" class="form-control form-control-sm" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <label>Durante as refeições</label>
                            <input type="text" readonly value="@Model?.DuranteAsRefeicoes" class="form-control form-control-sm" />
                        </div>
                        <div class="col-8">
                            <br />
                            <input type="text" readonly value="@Model?.ObsDuranteAsRefeicoes" class="form-control form-control-sm" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <label>Refrigerantes</label>
                            <input type="text" readonly value="@Model?.Refrigerantes" class="form-control form-control-sm" />
                        </div>
                        <div class="col-8">
                            <br />
                            <input type="text" readonly value="@Model?.ObsRefrigerantes" class="form-control form-control-sm" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <label>Açucares</label>
                            <input type="text" readonly value="@Model?.Acucares" class="form-control form-control-sm" />
                        </div>
                        <div class="col-8">
                            <br />
                            <input type="text" readonly value="@Model?.Acucares" class="form-control form-control-sm" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <label>Sódio</label>
                            <input type="text" readonly value="@Model?.Sodio" class="form-control form-control-sm" />
                        </div>
                        <div class="col-8">
                            <br />
                            <input type="text" readonly value="@Model?.ObsSodio" class="form-control form-control-sm" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <label>Cereais</label>
                            <input type="text" readonly value="@Model?.Cereais" class="form-control form-control-sm" />
                        </div>
                        <div class="col-8">
                            <br />
                            <input type="text" readonly value="@Model?.ObsCereais" class="form-control form-control-sm" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <label>Frutas</label>
                            <input type="text" readonly value="@Model?.Frutas" class="form-control form-control-sm" />
                        </div>
                        <div class="col-8">
                            <br />
                            <input type="text" readonly value="@Model?.ObsFrutas" class="form-control form-control-sm" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <label>Verduras</label>
                            <input type="text" readonly value="@Model?.Verduras" class="form-control form-control-sm" />
                        </div>
                        <div class="col-8">
                            <br />
                            <input type="text" readonly value="@Model?.Verduras" class="form-control form-control-sm" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <label>Local de almoço</label>
                            <input type="text" readonly value="@Model?.LocalAlmoco?.Descricao" class="form-control form-control-sm" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <label>Preferências</label>
                            <input type="text" readonly value="@Model?.Preferencias" class="form-control form-control-sm" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <label>Aversões</label>
                            <input type="text" readonly value="@Model?.Aversoes" class="form-control form-control-sm" />
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </div>
}
else
{
    <p class="text-center">Este paciente não possui registro de consumo alimentar. <a onclick="AbrirFormularioCadastrarEditarConsumos_OnClick('@ViewBag.Id','null')" class="btn btn-link">Cadastrar</a></p>
}

NutriSoftwareV1/Views/Consumos/Partiais/_FormularioConsumos.cshtml
@using NutriSoftwareV1.Enums
@model ConsumoAlimentar

<form name="frmCadastrarEditarConsumo" method="post" class="p-0 m-0">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">@ViewBag.Titulo</h5>
    </div>

    <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
                <input type="hidden" asp-for="PacienteId" value="@ViewBag.PacienteId" />
                <input type="hidden" asp-for="Id" value="@Model?.Id" />
                <div class="col-3">
                    <label>Água</label>
                   
                    <select asp-for="Agua" asp-items="@Html.GetEnumSelectList<EN_Afirmacao>()" class="form-select form-select-sm">
                        <option></option>
                    </select>
                </div>
                <div class="col-9">
                    <label>Obs</label>
                    <input type="text" asp-for="ObsAgua" class="form-control form-control-sm" />
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <label>Sucos</label>
                    <select asp-for="Sucos" asp-items="Html.GetEnumSelectList<EN_Afirmacao>()" class="form-select form-select-sm">
                        <option></option>
                    </select>
                </div>
                <div class="col-9">
                    <label>Obs</label>
                    <input type="text" asp-for="ObsSucos" class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row">
                <div class="col-3">
                    <label>Liq. Durante as refeições </label>
                    <select asp-for="DuranteAsRefeicoes" asp-items="Html.GetEnumSelectList<EN_Afirmacao>()" class="form-select form-select-sm">
                        <option></option>
                    </select>
                </div>
                <div class="col-9">
                    <label>Obs</label>
                    <input type="text" asp-for="ObsDuranteAsRefeicoes" class="form-control form-control-sm" />
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <label>Refrigerantes</label>
                    <select asp-for="Refrigerantes" asp-items="Html.GetEnumSelectList<EN_Afirmacao>()" class="form-select form-select-sm">
                        <option></option>
                    </select>
                </div>
                <div class="col-9">
                    <label>Obs</label>
                    <input type="text" asp-for="ObsRefrigerantes" class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row">
                <div class="col-3">
                    <label>Açucares</label>
                    <select asp-for="Acucares" asp-items="Html.GetEnumSelectList<EN_Afirmacao>()" class="form-select form-select-sm">
                        <option></option>
                    </select>
                </div>
                <div class="col-9">
                    <label>Obs</label>
                    <input type="text" asp-for="ObsAcucares" class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row">
                <div class="col-3">
                    <label>Sódio</label>
                    <select asp-for="Sodio" asp-items="Html.GetEnumSelectList<EN_Afirmacao>()" class="form-select form-select-sm">
                        <option></option>
                    </select>
                </div>
                <div class="col-9">
                    <label>Obs</label>
                    <input type="text" asp-for="ObsSodio" class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row">
                <div class="col-3">
                    <label>Cereais</label>
                    <select asp-for="Cereais" asp-items="Html.GetEnumSelectList<EN_Afirmacao>()" class="form-select form-select-sm">
                        <option></option>
                    </select>
                </div>
                <div class="col-9">
                    <label>Obs</label>
                    <input type="text" asp-for="ObsCereais" class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row">
                <div class="col-3">
                    <label>Frutas</label>
                    <select asp-for="Frutas" asp-items="Html.GetEnumSelectList<EN_Afirmacao>()" class="form-select form-select-sm">
                        <option></option>
                    </select>
                </div>
                <div class="col-9">
                    <label>Obs</label>
                    <input type="text" asp-for="ObsFrutas" class="form-control form-control-sm" />
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <label>Verduras</label>
                    <select asp-for="Verduras" asp-items="Html.GetEnumSelectList<EN_Afirmacao>()" class="form-select form-select-sm">
                        <option></option>
                    </select>
                </div>
                <div class="col-9">
                    <label>Obs</label>
                    <input type="text" asp-for="ObsVerduras" class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row">
                <div class="col-3">
                    <label>Local de almoço</label>
                    <select asp-for="LocalAlmocoId" asp-items="ViewBag.LocaisAlmoco" class="form-select form-select-sm">
                        <option></option>
                    </select>
                </div>
                <div class="col-9">
                    <label>Obs</label>
                    <input type="text" asp-for="LocalAlmoco" class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label>Preferências</label>
                    <input type="text" asp-for="Preferencias" class="form-control form-control-sm" />
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label>Aversões</label>
                    <input type="text" asp-for="Aversoes" class="form-control form-control-sm" />
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" onclick="CadastrarEditarConsumos_OnClick()" class="btn btn-primary">Save changes</button>
    </div>
</form>

NutriSoftwareV1/Views/Consumos/Partiais/_GeralConsumos.cshtml
@model ConsumoAlimentar
<div class="row">
    <div class="col-11 bcAzulMar bdr-20 pt-2 pb-2 bds-1">
        <div class="container-fluid">
            <div class="row" id="pnlConsumoPaciente">
                <partial name="Partiais/_DadosConsumoAlimentar" for="@Model" />
            </div>
        </div>
    </div>

    <div class="col-1 bcAzulMar" style="border-radius: 20px;">
        <div class="container-fluid">
            <div class="row">
                <div class="float-left" style="padding-bottom: 25px;">
                    <nav class="mt-5">
                        <ul class="m-0 p-0">
                            <li class="d-flex mt-5"><a href="@Url.Action("Index","Paciente", new {Id=ViewBag.Id})"><img src="~/icons-main/icons/person-badge.svg" alt="Dados Paciente" width="25" height="25" title="Dados Paciente"></a></li>
                            <li class="d-flex mt-5"><a href="@Url.Action("Index","Anminese", new{Id=ViewBag.Id})"><img src="~/icons-main/icons/clipboard.svg" alt="Anminese" width="25" height="25" title="Anminese"></a></li>
                            <li class="d-flex mt-5"><a href="@Url.Action("Index","Avaliacao",new{Id=ViewBag.Id})"><img src="~/icons-main/icons/table.svg" alt="Avaliações" width="25" height="25" title="Avaliações"></a></li>
                            <li class='d-flex mt-5'><a href="@Url.Action("Index","AvaliacaoBioImpedancia", new{Id=ViewBag.Id})"><img src='~/icons-main/icons/tablet-landscape.svg' alt='Bioimpedância' width='25' height='25' title='BioImpedância'></a></li>
                            @if (Model != null)
                            {
                                <li class="d-flex mt-5"><a onclick="AbrirFormularioCadastrarEditarConsumos_OnClick('@Model.PacienteId','@Model.Id')"><img src="~/icons-main/icons/pencil-square.svg" alt="Editar" width="25" height="25" title="Editar"></a></li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>