NutriSoftwareV1/Controllers/AnmineseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NutriSoftwareV1.Data;
using NutriSoftwareV1.Models;

namespace NutriSoftwareV1.Controllers
{
    public class AnmineseController : Controller
    {
        public IActionResult Index(long Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var anminese = db.Anminese
                    .Include(d => d.DiagnosticoMedico)
                    .Include(s => s.HistoricoFamiliar)
                    .Include(a => a.AtividadesFiscia)
                    .Include(p => p.Paciente)
                    .FirstOrDefault(p => p.PacienteId == Id);
                ViewBag.Id = Id;

                return View(anminese);
            }

        }

        [HttpGet]
        public IActionResult CadastrarEditarAnminese(long Id, int? AnmineseId = null)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                ViewBag.Titulo = "Cadastro de Anminese";
                if (AnmineseId.HasValue)
                {
                    var anminese = db.Anminese.Find(AnmineseId);
                    ViewBag.DiagnosticoMedico = ListaDoencas(db, anminese.DiagnosticoMedicoId);
                    ViewBag.HistoricoFamiliar = ListaDoencas(db, anminese.HistoricoFamiliarId);
                    ViewBag.AtividadesFisicas = ListaAtividadesFisicas(db, anminese.AtividadesFisciaId);
                    ViewBag.Titulo = "Alterar dados de  Anminese";
                    ViewBag.PacienteId = Id;
                    ViewBag.Id = Id;
                    return PartialView("Partiais/_FormularioAnminese", anminese);

                }
                ViewBag.PacienteId = Id;
                ViewBag.Id = Id;
                ViewBag.DiagnosticoMedico = ListaDoencas(db);
                ViewBag.HistoricoFamiliar = ListaDoencas(db);
                ViewBag.AtividadesFisicas = ListaAtividadesFisicas(db);
                return PartialView("Partiais/_FormularioAnminese");
            }
        }


        [HttpPost]
        public IActionResult CadastrarEditarAnminese(Anminese pAnminese)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                if (pAnminese.Id > 0)
                    db.Anminese.Update(pAnminese);
                else
                    db.Anminese.Add(pAnminese);

                db.SaveChanges();
                var anminese = db.Anminese.Include(d => d.DiagnosticoMedico)
                    .Include(s => s.HistoricoFamiliar)
                    .Include(a => a.AtividadesFiscia)
                    .Include(p => p.Paciente)
                    .FirstOrDefault(p => p.PacienteId == pAnminese.PacienteId);
                ViewBag.Id = pAnminese.PacienteId;
                return PartialView("Partiais/_GeralAnminese", anminese);
            }
        }
        public static SelectList ListaDoencas(NutriDbContext db, int? IdDoenca = null)
        {
            var doecas = db.Doenca.ToList();
            return new SelectList(doecas, "Id", "Descricao", IdDoenca);
        }

        public static SelectList ListaAtividadesFisicas(NutriDbContext db, int? IdAtividade = null)
        {
            var doecas = db.AtividadeFisica.ToList();
            return new SelectList(doecas, "Id", "Descricao", IdAtividade);
        }
    }
}

NutriSoftwareV1/Controllers/ConsumosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NutriSoftwareV1.Data;
using NutriSoftwareV1.Models;

namespace NutriSoftwareV1.Controllers
{
    public class ConsumosController : Controller
    {
        public IActionResult Index(long Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var consumos = db.ConsumoAlimentar
                    .Include(p=>p.Paciente)
                    .Include(l => l.LocalAlmoco)
                    .FirstOrDefault(p => p.PacienteId == Id);
                ViewBag.Id = Id;
                return View(consumos);
            }
        }

        [HttpGet]
        public IActionResult CadastrarEditarConsumos(long Id, int? ConsumosId = null)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                ViewBag.Titulo = "Cadastro de Consumo";
                if (ConsumosId.HasValue)
                {
                    var consumo = db.ConsumoAlimentar.Find(ConsumosId);
                    ViewBag.LocaisAlmoco = ListaLocaisAlmoco(db, consumo.LocalAlmocoId);
                 
                    ViewBag.Titulo = "Alterar dados de consumo";
                    ViewBag.PacienteId = Id;
                    ViewBag.Id = Id;
                    return PartialView("Partiais/_FormularioConsumos", consumo);

                }
                ViewBag.PacienteId = Id;
                ViewBag.Id = Id;
                ViewBag.LocaisAlmoco = ListaLocaisAlmoco(db);
                return PartialView("Partiais/_FormularioConsumos");
            }
        }


        [HttpPost]
        public IActionResult CadastrarEditarConsumos(ConsumoAlimentar pConsumo)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                if (pConsumo.Id > 0)
                    db.ConsumoAlimentar.Update(pConsumo);
                else
                    db.ConsumoAlimentar.Add(pConsumo);

                db.SaveChanges();
                var consumo = db.ConsumoAlimentar
                    .Include(p => p.Paciente)
                    .Include(l => l.LocalAlmoco)
                    .FirstOrDefault(p => p.PacienteId == pConsumo.PacienteId);
                ViewBag.Id = pConsumo.PacienteId;
                return PartialView("Partiais/_GeralConsumos", consumo);
            }
        }

        public static SelectList ListaLocaisAlmoco(NutriDbContext db, int ?id=null)
        {
            var locais = db.LocalAlmoco.ToList();
            return new SelectList(locais, "Id", "Descricao", id);
        }


    }
}

NutriSoftwareV1/Controllers/PacienteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NutriSoftwareV1.Data;
using NutriSoftwareV1.Models;
using Org.BouncyCastle.Asn1.Ocsp;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace NutriSoftwareV1.Controllers
{
    public class PacienteController : Controller
    {
        ErrorMessage errorMessage;

        [HttpGet]
        public IActionResult Index(long? Id, bool requestJs = false)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var pacientes = db.pacientes.Include(p => p.Anotacoes).OrderBy(p => p.Nome).ToList();
                if (Id.HasValue)
                {
                    ViewBag.DetalhePaciente = Id.Value;
                    ViewBag.DetalhePaciente = pacientes.FirstOrDefault(p => p.Id == Id.Value);
                    if (requestJs)
                        return PartialView("Partiais/_DetalhesPaciente", pacientes.FirstOrDefault(p => p.Id == Id.Value));
                }
                return View(pacientes);
            }
        }

        public IActionResult CadastrarEditarPaciente(long? Id)
        {
            using (NutriDbContext db =new NutriDbContext())
            {
                if (Id.HasValue)
                {
                    return PartialView("Partiais/_FormularioCadastrarEditarPaciente", db.pacientes.Find(Id));
                }
                return PartialView("Partiais/_FormularioCadastrarEditarPaciente", new Paciente());
            }
        }

        [HttpPost]
        public IActionResult Create(Paciente pPaciente)
        {
            if (!ModelState.IsValid)
            {
                errorMessage = new ErrorMessage();
                errorMessage.TituloErro = " validação(es)";
                ModelState.Values.Where(e => e.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid).ToList().ForEach(p =>
                {
                    errorMessage.MensagemDeErro += p.Errors[0].ErrorMessage;
                });

                string jsonStr = JsonSerializer.Serialize<ErrorMessage>(errorMessage);
                return StatusCode(500, jsonStr);
            }
            using (NutriDbContext db = new NutriDbContext())
            {
                pPaciente.Cpf = string.IsNullOrEmpty(pPaciente.Cpf) ? null : pPaciente.Cpf.Replace(".", "").Replace("-", "");

                db.pacientes.Add(pPaciente);
                db.SaveChanges();
                var pacienteCadastrado = db.pacientes.FirstOrDefault(p => p.Id == pPaciente.Id);

                return PartialView("Partiais/_DetalhesPaciente", pacienteCadastrado);
            }
        }

        [HttpPost]
        public IActionResult Edit(Paciente pPaciente)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                if (!string.IsNullOrEmpty(pPaciente.Cpf))
                    pPaciente.Cpf = pPaciente.Cpf.Replace(".", "").Replace("-", "");

                if (!string.IsNullOrEmpty(pPaciente.Telefone))
                    pPaciente.Telefone = RemoverMascaraTelefone(pPaciente.Telefone);
                db.pacientes.Update(pPaciente);
                db.SaveChanges();
                var pacienteCadastrado = db.pacientes.FirstOrDefault(p => p.Id == pPaciente.Id);

                return PartialView("Partiais/_DetalhesPaciente", pacienteCadastrado);
            }
        }


        [HttpPost]
        public IActionResult Delete(long Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var paciente = db.pacientes.Find(Id);
                var anotacoes = db.AnotacosPaciente.Where(p => p.PacienteId == Id).ToList();
                var avaliacoes = db.AvaliacoesFisicas.Where(p => p.PacienteId == Id).ToList();
                var avaliacoesBio = db.AvalicaoBioImpedancia.Where(p => p.PacienteId == Id).ToList();
                if (anotacoes.Count > 0)
                    db.AnotacosPaciente.RemoveRange(anotacoes);

                if (avaliacoes.Count > 0)
                    db.AvaliacoesFisicas.RemoveRange(avaliacoes);

                if (avaliacoesBio.Count > 0)
                    db.AvalicaoBioImpedancia.RemoveRange(avaliacoesBio);

                db.pacientes.Remove(paciente);
                db.SaveChanges();
                var pacientes = db.pacientes.OrderBy(p => p.Nome).ToList();

                return PartialView("Partiais/_GeralPaciente", pacientes);
            }
        }


        #region Anotacões
        public IActionResult ObservacoesPaciente(long Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var anotacoes = db.pacientes.Include(p => p.Anotacoes).FirstOrDefault(p => p.Id == Id);
                var pacienteAnotacoes = anotacoes == null ? new Paciente { Id = Id } : anotacoes;
                return PartialView("Partiais/_AnotacoesPaciente", pacienteAnotacoes);
            }
        }

        [HttpGet]
        public IActionResult CadastrarAnotacaoPaciente(int Id)
        {
            ViewBag.TitleModalAnotacoes = "Cadastro de anotações";
            ViewBag.BotaoTituloCadastroAnotacoes = "Salvar";
            ViewBag.DetalhePaciente = Id;
            return PartialView("Partiais/_FormularioCadastrarEditarAnotacaoPaciente", new Observacao { PacienteId = Id, DataObservacao=DateTime.Now});

        }
        [HttpPost]
        public IActionResult CadastrarAnotacaoPaciente(Observacao pAnotacao)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                db.AnotacosPaciente.Add(pAnotacao);
                db.SaveChanges();
                var anotacoesPaciente = db.pacientes.Include(p => p.Anotacoes).FirstOrDefault(p=>p.Id == pAnotacao.PacienteId);

                return PartialView("Partiais/_AnotacoesPaciente", anotacoesPaciente);
            }
        }
        [HttpGet]
        public IActionResult EditarAnotacaoPaciente(int Id)
        {
            ViewBag.TitleModalAnotacoes = "Alteração de anotação";
            ViewBag.BotaoTituloCadastroAnotacoes = "Salvar alterações";
            using (NutriDbContext db = new NutriDbContext())
            {
                var anotacao = db.AnotacosPaciente.Include(p => p.Paciente).FirstOrDefault(p => p.Id == Id);

                return PartialView("Partiais/_FormularioCadastrarEditarAnotacaoPaciente", anotacao);
            }
        }

        [HttpPost]
        public IActionResult EditarAnotacaoPaciente(Observacao pAnotacao)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                db.AnotacosPaciente.Update(pAnotacao);
                db.SaveChanges();
                var anotacoesPaciente = db.pacientes.Include(a=>a.Anotacoes).FirstOrDefault(p=>p.Id==pAnotacao.PacienteId);
                return PartialView("Partiais/_AnotacoesPaciente", anotacoesPaciente);
            }
        }

        [HttpPost]
        public IActionResult RemoverAnotacaoPaciente(int Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var anotacao = db.AnotacosPaciente.Find(Id);
                var idPaciente = anotacao.PacienteId;
                db.AnotacosPaciente.Remove(anotacao);
                db.SaveChanges();
                var anotacoesPaciente = db.pacientes.Include(a=>a.Anotacoes).FirstOrDefault(p=>p.Id== idPaciente);
                return PartialView("Partiais/_AnotacoesPaciente", anotacoesPaciente);
            }
        }


        #endregion

        public static string RemoverMascaraTelefone(string telefone)
        {
            // Remove caracteres não numéricos
            string numeroLimpo = Regex.Replace(telefone, @"[^\d]", "");

            return numeroLimpo;
        }

    }
}

NutriSoftwareV1/Views/Avaliacao/Index.cshtml
@model NutriSoftwareV1.Models.Paciente


<div class="container-fluid" style="margin-top: 70px;">
    <div class="row">
        <div class="col-11 bcAzulMar bdr-20 pt-2 pb-2 bds-1">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 bg-secondary p-1 bdr-5"><h5 class="text-center text-light p-0 m-0">Paciente: <b>@Model.Nome</b> | Idade: <b>@Model?.Idade anos</b> | Altura:<b>@Model?.Altura</b></h5></div>
                    <div class="col-12 p-0">
                        <div class="row">


                            <div class="col-2 p-0 d-inline-block mt-1">
                                <div class="container-fluid mt-1 pe-0">
                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>Avaliações:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>Data:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>Peso:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-light borderTopSolidWhite text-secondary text-xl-center"><b>Circunferências</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>C.Cintura:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>C.Abdominal:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>C.Quadril:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>C.Peito:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>C.Braço D:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>C.Braço E:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>C.Coxa D:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>C.Coxa E:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>C.Panturrilha D:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>C.Panturrilha E:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-light borderTopSolidWhite text-secondary text-center"><b>Dobra cutânea</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>DC.Triceps:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>DC.Escapular:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>DC.Supra Iliaca:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>DC.Abdominal:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>DC.Axilar:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>DC.Peitoral:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>DC.Coxa:</b></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>% Gordura:</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>KG M.Muscular</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 bg-secondary borderTopSolidWhite text-light"><b>KG Gordura</b></div>
                                    </div>


                                </div>
                            </div>
                            <div class="col-10 d-inline-block mt-1 ps-3" id="pnlAvaliacoesPaciente">
                                <partial name="Partiais/_ListaAvaliacoes" for="@Model.Avaliacoes" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-1 bcAzulMar" style="border-radius: 20px;">
            <div class="container-fluid">
                <div class="row">
                    <div class="float-left">
                        <nav class="mt-5">
                            <ul class="m-0 p-0">
                                <li class="d-flex mt-5"><a href="@Url.Action("Index","Paciente", new {Id=Model.Id})"><img src="~/icons-main/icons/person-badge.svg" alt="Dados Paciente" width="25" height="25" title="Dados Paciente"></a></li>
                                <li class="d-flex mt-5"><a href="@Url.Action("Index","AvaliacaoBioImpedancia",new {Id=Model.Id})"><img src="~/icons-main/icons/tablet-landscape.svg" alt="Bioimpedância" width="25" height="25" title="BioImpedância"></a></li>
                                <li class="d-flex mt-5"><a href="@Url.Action("Index", "Anminese", new { Id = Model.Id })"><img src="~/icons-main/icons/clipboard.svg" alt="Anminese" width="25" height="25" title="Anminese"></a></li>
                                <li class="d-flex mt-5"><a href="@Url.Action("Index", "Consumos", new { Id = Model.Id })"><img src="~/icons-main/icons/basket2.svg" alt="Consumos" width="25" height="25" title="Consumos"></a></li>
                                <li class="d-flex mt-5"><a href="#"><img src="~/icons-main/icons/eye-fill.svg" alt="Visualizar" width="25" height="25" title="Visualizar"></a></li>
                                <li class="d-flex mt-5"><a onclick="AbrirFormularioCadastrarEditarAvaliacao_OnClick('@Model?.Id',null)"><img src="~/icons-main/icons/plus-square-fill.svg" alt="Cadastrar Nova" width="25" height="25" title="Cadastrar Nova"></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalCadastroAvalicao" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="pnlFomularioAvaliacao">
            @* Carregamento via jquery *@
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_AvaliacaoScriptsPartial");
    }
}