NutriSoftwareV1/Controllers/AnmineseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NutriSoftwareV1.Data;
using NutriSoftwareV1.Models;

namespace NutriSoftwareV1.Controllers
{
    public class AnmineseController : Controller
    {
        public IActionResult Index(long Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var anminese = db.Anminese
                    .Include(d => d.DiagnosticoMedico)
                    .Include(s => s.HistoricoFamiliar)
                    .Include(a => a.AtividadesFiscia)
                    .Include(p => p.Paciente)
                    .FirstOrDefault(p => p.PacienteId == Id);
                ViewBag.Id = Id;

                return View(anminese);
            }

        }

        [HttpGet]
        public IActionResult CadastrarEditarAnminese(long Id, int? AnmineseId = null)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                ViewBag.Titulo = "Cadastro de Anminese";
                if (AnmineseId.HasValue)
                {
                    var anminese = db.Anminese.Find(AnmineseId);
                    ViewBag.DiagnosticoMedico = ListaDoencas(db, anminese.DiagnosticoMedicoId);
                    ViewBag.HistoricoFamiliar = ListaDoencas(db, anminese.HistoricoFamiliarId);
                    ViewBag.AtividadesFisicas = ListaAtividadesFisicas(db, anminese.AtividadesFisciaId);
                    ViewBag.Titulo = "Alterar dados de  Anminese";
                    ViewBag.PacienteId = Id;
                    ViewBag.Id = Id;
                    return PartialView("Partiais/_FormularioAnminese", anminese);

                }
                ViewBag.PacienteId = Id;
                ViewBag.Id = Id;
                ViewBag.DiagnosticoMedico = ListaDoencas(db);
                ViewBag.HistoricoFamiliar = ListaDoencas(db);
                ViewBag.AtividadesFisicas = ListaAtividadesFisicas(db);
                return PartialView("Partiais/_FormularioAnminese");
            }
        }


        [HttpPost]
        public IActionResult CadastrarEditarAnminese(Anminese pAnminese)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                if (pAnminese.Id > 0)
                    db.Anminese.Update(pAnminese);
                else
                    db.Anminese.Add(pAnminese);

                db.SaveChanges();
                var anminese = db.Anminese.Include(d => d.DiagnosticoMedico)
                    .Include(s => s.HistoricoFamiliar)
                    .Include(a => a.AtividadesFiscia)
                    .Include(p => p.Paciente)
                    .FirstOrDefault(p => p.PacienteId == pAnminese.PacienteId);
                ViewBag.Id = pAnminese.PacienteId;
                return PartialView("Partiais/_GeralAnminese", anminese);
            }
        }
        public static SelectList ListaDoencas(NutriDbContext db, int? IdDoenca = null)
        {
            var doecas = db.Doenca.ToList();
            return new SelectList(doecas, "Id", "Descricao", IdDoenca);
        }

        public static SelectList ListaAtividadesFisicas(NutriDbContext db, int? IdAtividade = null)
        {
            var doecas = db.AtividadeFisica.ToList();
            return new SelectList(doecas, "Id", "Descricao", IdAtividade);
        }
    }
}

NutriSoftwareV1/Controllers/AvaliacaoBioImpedanciaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NutriSoftwareV1.Data;
using NutriSoftwareV1.Dto;
using NutriSoftwareV1.Models;
using System.Text.Json;

namespace NutriSoftwareV1.Controllers
{
    public class AvaliacaoBioImpedanciaController : Controller
    {
        ErrorMessage errorMessage;
        public IActionResult Index(long Id)
        {
            using (NutriDbContext db = new NutriDbContext()) 
            {
                var bio = db.pacientes.Include(b => b.AvaliacoesBioImpedancia).FirstOrDefault(p => p.Id == Id);
                return View(bio);
            }
              
        }


        [HttpGet]
        public IActionResult CadastrarEditarAvaliacaoBioImpedancia(long Id, long? AvaliacoaId)
        {
            DtoCadastroAvaliacaoBioImpedancia dtoCadastroAvaliacaoBio = new DtoCadastroAvaliacaoBioImpedancia();
            dtoCadastroAvaliacaoBio.PacienteId = Id;
            dtoCadastroAvaliacaoBio.TituloCadastarEditar = "Cadastrar Avaliação";
            dtoCadastroAvaliacaoBio.Data = DateTime.Now;

            using (NutriDbContext db = new NutriDbContext())
            {
                var avaliacoes = db.AvalicaoBioImpedancia.Include(p => p.Paciente).Where(p => p.PacienteId == Id).OrderBy(p => p.Data).ToList();
                dtoCadastroAvaliacaoBio.UltimaAvalicao = avaliacoes.LastOrDefault();
                if (AvaliacoaId.HasValue)
                {
                    dtoCadastroAvaliacaoBio.TituloCadastarEditar = "Editar Avaliação";
                    dtoCadastroAvaliacaoBio.CriarAtulizar = db.AvalicaoBioImpedancia.Find(AvaliacoaId.Value);
                    dtoCadastroAvaliacaoBio.Data = dtoCadastroAvaliacaoBio.CriarAtulizar.Data;
                }
            }
            return PartialView("Partiais/_FormularioAvaliacaoBioImpedancia", dtoCadastroAvaliacaoBio);


        }


        [HttpPost]
        public IActionResult CadastrarEditarAvaliacaoBioImpedancia(AvalicaoBioImpedancia pAvaliacao)
        {
            if (!ModelState.IsValid)
            {
                errorMessage = new ErrorMessage();
                errorMessage.TituloErro = "validação(es)";
                ModelState.Values.Where(e => e.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid).ToList().ForEach(p =>
                {
                    errorMessage.MensagemDeErro += p.Errors[0].ErrorMessage;
                });

                string jsonStr = JsonSerializer.Serialize<ErrorMessage>(errorMessage);
                return StatusCode(500, jsonStr);
            }

            using (NutriDbContext db = new NutriDbContext())
            {
                if (pAvaliacao?.Id > 0)
                    db.AvalicaoBioImpedancia.Update(pAvaliacao);
                else
                    db.AvalicaoBioImpedancia.Add(pAvaliacao);
                db.SaveChanges();
                return PartialView("Partiais/_ListaAvaliacoesBioImpedancia", db.AvalicaoBioImpedancia.Include(p => p.Paciente).Where(p => p.PacienteId == pAvaliacao.PacienteId).ToList());
            }
        }

        [HttpPost]
        public IActionResult Delete(long Id)
        {
            try
            {

                using (NutriDbContext db = new NutriDbContext())
                {
                    var avaliacao = db.AvalicaoBioImpedancia.Find(Id);
                    var pacienteId = avaliacao.PacienteId;
                    db.Remove(avaliacao);
                    db.SaveChanges();

                    return PartialView("Partiais/_ListaAvaliacoesBioImpedancia", db.AvalicaoBioImpedancia.Include(p => p.Paciente).Where(p => p.PacienteId == pacienteId).ToList());
                }
            }
            catch (Exception ex)
            {
                errorMessage = new ErrorMessage();
                errorMessage.TituloErro = "Exception";
                errorMessage.MensagemDeErro = !string.IsNullOrEmpty(ex?.InnerException?.Message) ? ex.InnerException.Message : ex.Message;
                string jsonStr = JsonSerializer.Serialize<ErrorMessage>(errorMessage);
                return StatusCode(500, jsonStr);
            }
        }
    }
}

NutriSoftwareV1/Controllers/ConsumosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NutriSoftwareV1.Data;
using NutriSoftwareV1.Models;

namespace NutriSoftwareV1.Controllers
{
    public class ConsumosController : Controller
    {
        public IActionResult Index(long Id)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                var consumos = db.ConsumoAlimentar
                    .Include(p=>p.Paciente)
                    .Include(l => l.LocalAlmoco)
                    .FirstOrDefault(p => p.PacienteId == Id);
                ViewBag.Id = Id;
                return View(consumos);
            }
        }

        [HttpGet]
        public IActionResult CadastrarEditarConsumos(long Id, int? ConsumosId = null)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                ViewBag.Titulo = "Cadastro de Consumo";
                if (ConsumosId.HasValue)
                {
                    var consumo = db.ConsumoAlimentar.Find(ConsumosId);
                    ViewBag.LocaisAlmoco = ListaLocaisAlmoco(db, consumo.LocalAlmocoId);
                 
                    ViewBag.Titulo = "Alterar dados de consumo";
                    ViewBag.PacienteId = Id;
                    ViewBag.Id = Id;
                    return PartialView("Partiais/_FormularioConsumos", consumo);

                }
                ViewBag.PacienteId = Id;
                ViewBag.Id = Id;
                ViewBag.LocaisAlmoco = ListaLocaisAlmoco(db);
                return PartialView("Partiais/_FormularioConsumos");
            }
        }


        [HttpPost]
        public IActionResult CadastrarEditarConsumos(ConsumoAlimentar pConsumo)
        {
            using (NutriDbContext db = new NutriDbContext())
            {
                if (pConsumo.Id > 0)
                    db.ConsumoAlimentar.Update(pConsumo);
                else
                    db.ConsumoAlimentar.Add(pConsumo);

                db.SaveChanges();
                var consumo = db.ConsumoAlimentar
                    .Include(p => p.Paciente)
                    .Include(l => l.LocalAlmoco)
                    .FirstOrDefault(p => p.PacienteId == pConsumo.PacienteId);
                ViewBag.Id = pConsumo.PacienteId;
                return PartialView("Partiais/_GeralConsumos", consumo);
            }
        }

        public static SelectList ListaLocaisAlmoco(NutriDbContext db, int ?id=null)
        {
            var locais = db.LocalAlmoco.ToList();
            return new SelectList(locais, "Id", "Descricao", id);
        }


    }
}

NutriSoftwareV1/Views/AvaliacaoBioImpedancia/Index.cshtml
@model NutriSoftwareV1.Models.Paciente


<div class="container-fluid" style="margin-top: 70px;">
    <div class="row">
        <div class="col-11 bcAzulMar bdr-20 pt-2 pb-2 bds-1">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 bg-secondary p-1 bdr-5"><h5 class="text-center text-light p-0 m-0">Paciente: <b>@Model.Nome</b> | Idade: <b>@Model?.Idade anos</b> | Altura:<b>@Model?.Altura</b></h5></div>
                    <div class="col-12 p-0">
                        <div class="row">


                            <div class="col-2 p-0 d-inline-block mt-1">
                                <div class="container-fluid mt-1 pe-0">

                                    <div class="row">
                                        <div class="col-12 p-2 bg-secondary borderTopSolidWhite text-light"><b>Data</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 p-2 bg-secondary borderTopSolidWhite text-light"><b>Peso</b></div>
                                    </div>


                                    <div class="row">
                                        <div class="col-12 p-2 bg-secondary borderTopSolidWhite text-light"><b>IMC</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 p-2 bg-secondary borderTopSolidWhite text-light"><b>% Gorudura corporal</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 p-2 bg-secondary borderTopSolidWhite text-light"><b>% Musc. Esquelético</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 p-2 bg-secondary borderTopSolidWhite text-light"><b>Met. Basal</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 p-2 bg-secondary borderTopSolidWhite text-light"><b>Idade corporal</b></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-12 p-2 bg-secondary borderTopSolidWhite text-light"><b>Gord.Veceral</b></div>
                                    </div>

                                </div>
                            </div>
                            <div class="col-10 d-inline-block mt-1 ps-3" id="pnlAvaliacoesBioImpedanciaPaciente">
                                <partial name="Partiais/_ListaAvaliacoesBioImpedancia" for="@Model.AvaliacoesBioImpedancia" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-1 bcAzulMar" style="border-radius: 20px;">
            <div class="container-fluid">
                <div class="row">
                    <div class="float-left">
                        <nav class="mt-5">
                            <ul class="m-0 p-0">
                                <li class="d-flex mt-5"><a href="@Url.Action("Index","Paciente", new {Id=Model.Id})"><img src="~/icons-main/icons/person-badge.svg" alt="Dados Paciente" width="25" height="25" title="Dados Paciente"></a></li>
                                <li class="d-flex mt-5"><a href="@Url.Action("Index","AvaliacaoBioImpedancia", new {Id=Model.Id})"><img src="~/icons-main/icons/tablet-landscape.svg" alt="Bioimpedância" width="25" height="25" title="BioImpedância"></a></li>
                                <li class="d-flex mt-5"><a href="@Url.Action("Index","Anminese", new {Id=Model.Id})"><img src="~/icons-main/icons/clipboard.svg" alt="Anminese" width="25" height="25" title="Anminese"></a></li>
                                <li class="d-flex mt-5"><a href="@Url.Action("Index","Consumos", new {Id=Model.Id})"><img src="~/icons-main/icons/basket2.svg" alt="Consumos" width="25" height="25" title="Consumos"></a></li>
                                <li class="d-flex mt-5"><a href="#"><img src="~/icons-main/icons/eye-fill.svg" alt="Visualizar" width="25" height="25" title="Visualizar"></a></li>
                                <li class="d-flex mt-5"><a onclick="AbrirFormularioCadastrarEditarAvaliacaoBioImpedancia_OnClick('@Model?.Id',null)"><img src="~/icons-main/icons/plus-square-fill.svg" alt="Cadastrar Nova" width="25" height="25" title="Cadastrar Nova"></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalCadastroAvalicaoBioImpedancia" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="pnlFomularioAvaliacaoBioImpedancia">
            @* Carregamento via jquery *@
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_AvaliacaoBioImpedanciaScriptsPartial");
    }
}